# Generated by Django 2.1 on 2018-08-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=512)),
                ('icon', models.ImageField(blank=True, upload_to='media/icons/%Y/%m/%d/', verbose_name='Иконка')),
                ('date', models.DateField(auto_now_add=True)),
                ('checked', models.NullBooleanField()),
            ],
            options={
                'verbose_name': 'Иконка',
                'verbose_name_plural': 'Иконки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=512)),
                ('icon', models.ImageField(blank=True, upload_to='media/groups/%Y/%m/%d/', verbose_name='Иконка')),
                ('child_groups', models.PositiveIntegerField(verbose_name='Дочерние группы')),
                ('child_elems', models.PositiveIntegerField(verbose_name='Дочерние элементы')),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='groups.Group', verbose_name='Родительская группа')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='elem',
            name='parent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Elem_parent_group', to='groups.Group', verbose_name='Родительская группа'),
        ),
    ]
