# Generated by Django 2.1 on 2018-08-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elem',
            name='parent_group',
        ),
        migrations.AddField(
            model_name='elem',
            name='elem_parent_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Elem_parent_group', to='groups.Group', verbose_name='Родительская группа элемента'),
            preserve_default=False,
        ),
    ]
