# Generated by Django 2.1 on 2018-08-03 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20180803_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='child_elems',
            field=models.PositiveIntegerField(blank=True, verbose_name='Дочерние элементы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='child_groups',
            field=models.PositiveIntegerField(blank=True, verbose_name='Дочерние группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='groups.Group', verbose_name='Родительская группа'),
        ),
    ]
