# Generated by Django 2.1 on 2018-08-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20180803_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='child_elems',
        ),
        migrations.RemoveField(
            model_name='group',
            name='child_groups',
        ),
        migrations.AlterField(
            model_name='elem',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='elem',
            name='icon',
            field=models.ImageField(blank=True, upload_to='elems/%Y/%m/%d/', verbose_name='Элемент'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(blank=True, upload_to='groups/%Y/%m/%d/', verbose_name='Иконка'),
        ),
    ]
